file = open("student.txt","w")
file.write("Name : Mimi\n")
file.write("Age : 16")
file.close()
print("Data Save Successfully")

file = open("student.txt","r")
print(file.read())
file.close()

file = open("student.txt","a")
file.write("\nClass : XI")
file.close()
file = open("student.txt","r")
print(file.read())
file.close()

file = open("quotes.txt","w")
file.write("Never give up\n")
file.write("Practice makes you ready becuse no one is perfect\n")
file.write("Dreaming big make impossible possible")
file.close()
print("Quotes saved")
file = open("quotes.txt","r")
print(file.read())
file.close()

t1 = input("Enter your task 1 :")
t2 = input("Enter your task 2 :")
t3 = input("Enter your task 3 :")
file = open("Todo.txt","w")
file.write(t1 + "\n")
file.write(t2 + "\n")
file.write(t3 + "\n")
file.close()
print("\n Today's Tasks \n")
file = open("todo.txt","r")
print(file.read())
file.close()

l = input("Enter things to learn :")
l1 = input("Enter things to learn :")
l2 = input("Enter things to learn :")
file = open("THINGS TO LEARN","w")
file.write(l+"\n")
file.write(l1+"\n")
file.write(l2+"\n")
file.close()
print("\n THINGS TO LEARN \n")
file = open("THINGS TO LEARN","r")
print(file.read())
file.close()